### PR TITLE
Fix collapse/expand bug on accordion title change.

### LINKED ISSUE #137: Accordion changing from open to closed when it shouldn't.
Originally reported by @mwcraig in ipython/ipython

----

In IPython 3.2/Python 3.4/Chrome 43.0.2357.130 , if I create an `Accordion` in one cell, then set its title in another cell, the  `Accordion` changes from open to closed.

A notebook to reproduce is at: http://nbviewer.ipython.org/gist/mwcraig/f026324a1749b00087ba

As mentioned in the notebook, `set_title` needs to be in a separate cell from `display` to expose the bug.

### PR DESCRIPTION
**Pull request by jdfreder**
closes #137

### CODE REVIEW

**Comment by jdfreder** [comment]
@SylvainCorlay @jasongrout this has been around for a couple of days, do either of you want to review or merge it?

File: ipywidgets/static/widgets/js/widget_selectioncontainer.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ define([
             this.containers = [];
             this.model_containers = {};
             this.children_views = new widget.ViewList(this.add_child_view, this.remove_child_view, this);
-            this.listenTo(this.model, 'change:children', function(model, value) {
+            this.listenTo(this.model, 'change:children', function(model, value, options) {
```
Comment (SylvainCorlay) [inline ipywidgets/static/widgets/js/widget_selectioncontainer.js]: why adding options here?

Comment (jdfreder) [inline ipywidgets/static/widgets/js/widget_selectioncontainer.js]: Not sure, I think I was using it elsewhere and accidentally added it here.  Shouldn't cause any harm though.
